version: '3'
services:

  roach-1:
    hostname: "roach1"
    image: cockroachdb/cockroach
    command: start --insecure --join=localhost:26257
    ports:
      - 26258:26257
    volumes:
      - ./data/roach-1:/cockroach/cockroach-data
