version: '3'
services:

  roach-ui:
    hostname: "roach-ui"
    image: cockroachdb/cockroach
    ports:
      - 8081:8080
      - 26257:26257
    networks:
      - cockroachnet
    volumes:
      - ./data/roach-ui:/cockroach/cockroach-data
      - ./init_db.sh:/init_db.sh
    entrypoint: "/bin/bash"
    command: "/init_db.sh"

  #roach-1:
  #  hostname: "roach1"
  #  image: cockroachdb/cockroach
  #  command: start --insecure --join=roach-ui
  #  depends_on:
  #    - roach-ui
  #  networks:
  #    - cockroachnet
  #  volumes:
  #    - ./data/roach-1:/cockroach/cockroach-data

  flask-app:
    hostname: "app"
    image: python:3
    volumes:
      - ./../:/devel/
    command: ["bash", "/devel/.docker/python/startup.sh"]
    ports:
      - 8080:8080
    depends_on:
      - roach-ui
    networks:
      - cockroachnet

networks:
  cockroachnet: